# Generated by Django 4.0.3 on 2022-04-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0032_alter_choice_response'),
        ('accounts', '0002_profile_correct_answers_profile_questions_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choices',
            field=models.ManyToManyField(null=True, to='question.choice'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_answered_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='questions_answered',
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_answered',
            field=models.ManyToManyField(null=True, to='question.question'),
        ),
    ]
