# Generated by Django 4.0.3 on 2022-04-19 05:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_choices_profile_questions_answered_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
