# Generated by Django 4.0.3 on 2022-03-27 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='images/')),
                ('outcome', models.BooleanField(null=True)),
                ('datePosted', models.DateTimeField(default=datetime.datetime.today)),
                ('dateEnds', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
