# Generated by Django 4.0.2 on 2022-04-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_question_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='vote',
            new_name='voters',
        ),
    ]
