# Generated by Django 4.0.3 on 2022-04-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_choice_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
