# Generated by Django 4.0.3 on 2022-04-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avg_w_score_no',
            field=models.FloatField(null=True, verbose_name='avgN'),
        ),
        migrations.AddField(
            model_name='question',
            name='avg_w_score_yes',
            field=models.FloatField(null=True, verbose_name='avgY'),
        ),
        migrations.AddField(
            model_name='question',
            name='equal_w_score_no',
            field=models.FloatField(null=True, verbose_name='equalN'),
        ),
        migrations.AddField(
            model_name='question',
            name='equal_w_score_yes',
            field=models.FloatField(null=True, verbose_name='equalY'),
        ),
    ]
