# Generated by Django 4.0.3 on 2022-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_question_avg_w_score_no_question_avg_w_score_yes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(to='question.question'),
        ),
    ]
