# Generated by Django 4.0.3 on 2022-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_remove_choice_question_choice_question_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answered',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
        migrations.AlterField(
            model_name='question',
            name='result',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
