# Generated by Django 4.0.3 on 2022-04-15 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0025_alter_question_dateends_alter_question_dateposted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
