# Generated by Django 4.0.3 on 2022-04-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0028_remove_question_category_question_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
