# Generated by Django 4.0.3 on 2022-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0030_question_category_alter_question_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, to='question.choice'),
        ),
    ]
