# Generated by Django 4.0.3 on 2022-04-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0031_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='response',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
