# Generated by Django 4.0.3 on 2022-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0037_remove_choice_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answered',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
